/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.ChitietphieunhapBLL;
import BLL.PhieunhapBLL;
import BLL.SanphamBLL;
import DTO.ChitietphieunhapDTO;
import DTO.PhieunhapDTO;
import DTO.SanphamDTO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class PhieunhapGUI extends javax.swing.JInternalFrame {

    PhieunhapBLL pnBLL = new PhieunhapBLL();
    private ArrayList<PhieunhapDTO> listPN;
    DefaultTableModel model;
    ChitietphieunhapBLL ctpnBLL = new ChitietphieunhapBLL();
    private ArrayList<ChitietphieunhapDTO> listCTPN;
    DefaultTableModel model1;
    SanphamBLL spBLL = new SanphamBLL();
    private ArrayList<SanphamDTO> listSP;
    DefaultTableModel modelsp;

    public PhieunhapGUI() {
        initComponents();
         try {
            UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(PhieunhapGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        pnBLL.loadComboboxMaNV(this.cbManv);
        pnBLL.loadComboboxMaNCC(this.cbMancc);
        listPN = pnBLL.getAllPhieunhapDTO();
        model = (DefaultTableModel) tblPhieunhap.getModel();
        model.setColumnIdentifiers(new Object[]{
            "STT", "Mã PN", "Mã NV", "Mã NCC", "Tổng tiền", "Ngày lập"
        });
        showTable();
        //-------
        txtTongtien.setText("0");
        txtTongtien.setEditable(false);
        txtNgaylap.setDate(new Date());
        //-------
        tblPhieunhap.setRowSorter(new TableRowSorter<TableModel>(model));
        txtTimkiemhoadonnhaphang.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateFilter();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateFilter();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateFilter();
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhieunhap = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        cbManv = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        cbMancc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JTextField();
        txtNgaylap = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        cbTimkimhoadonnhaphang = new javax.swing.JComboBox<>();
        txtTimkiemhoadonnhaphang = new javax.swing.JTextField();
        txtMP = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblChitietphieunhap = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        cbMasp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDongianhap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtThanhtien = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btnThem1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        cbMahdnh1 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSanpham = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtTongtienphieunhap = new javax.swing.JTextField();

        setTitle("Phiếu nhập_Chi tiết phiếu nhập");

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu nhập", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(255, 51, 51))); // NOI18N

        tblPhieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPhieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhieunhapMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPhieunhap);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã HDNH :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mã NV :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mã NCC :");

        jScrollPane3.setViewportView(cbManv);

        jScrollPane4.setViewportView(cbMancc);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText(" Tổng tiền :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText(" Ngày lập :");

        txtNgaylap.setDateFormatString("yyyy-MM-dd");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sua.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.setBorder(null);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setBorder(null);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        cbTimkimhoadonnhaphang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã HDNH", "Mã NCC", "Mã NV", "Ngày lập" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(cbTimkimhoadonnhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(txtTimkiemhoadonnhaphang, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbTimkimhoadonnhaphang, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txtTimkiemhoadonnhaphang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtMP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgaylap, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaylap, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(5, 5, 5))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết phiếu nhập", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 0, 0))); // NOI18N

        tblChitietphieunhap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblChitietphieunhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChitietphieunhapMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblChitietphieunhap);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Mã HDNH :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText(" Mã SP :");

        jScrollPane7.setViewportView(cbMasp);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText(" Đơn giá nhập :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText(" Số lượng :");

        txtSoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoluongActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText(" Thành tiền :");

        txtThanhtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThanhtienActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/them.png"))); // NOI18N
        btnThem1.setText("Thêm");
        btnThem1.setBorder(null);
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sua.png"))); // NOI18N
        btnSua1.setText("Sửa");
        btnSua1.setBorder(null);
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xoa.png"))); // NOI18N
        btnXoa1.setText("Xóa");
        btnXoa1.setBorder(null);
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btnReset1.setText("Reset");
        btnReset1.setBorder(null);
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSua1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(btnXoa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReset1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jScrollPane6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane6MouseClicked(evt);
            }
        });

        tblSanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanphamMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblSanpham);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(txtDongianhap)
                    .addComponent(cbMahdnh1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSoluong))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtThanhtien))))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbMahdnh1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtThanhtien, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDongianhap, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLabel14.setText("Tổng tiền :");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTongtienphieunhap, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTongtienphieunhap, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPhieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhieunhapMouseClicked
        //---------------------SHOW TEXTFIELD PHIEU NHAP-----------------//

        int i = tblPhieunhap.getSelectedRow();
        txtMP.setText(tblPhieunhap.getModel().getValueAt(i, 1).toString());//cái này lấy ko lên , ko hiểu sao luôn
        cbManv.setSelectedItem(tblPhieunhap.getModel().getValueAt(i, 2).toString());
        cbMancc.setSelectedItem(tblPhieunhap.getModel().getValueAt(i, 3).toString());
        txtTongtien.setText(tblPhieunhap.getModel().getValueAt(i, 4).toString());
        try {
            Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) model.getValueAt(i, 5));
            txtNgaylap.setDate(date);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        //----------------------------SET_Enabled--------------------------
        btnThem.setEnabled(false);
        txtTongtien.setEditable(false);
        txtNgaylap.setEnabled(false);
        txtMP.setEditable(false);
        txtTongtienphieunhap.setText(tblPhieunhap.getModel().getValueAt(i, 4).toString());
        //
        listCTPN = ctpnBLL.getChitietphieunhapDTO(tblPhieunhap.getModel().getValueAt(i, 1).toString());
        model1 = (DefaultTableModel) tblChitietphieunhap.getModel();
        model1.setColumnIdentifiers(new Object[]{
            "STT", "Mã Phiếu nhập", "Mã SP", "Số lượng", "Đơn giá nhập ", "Thành tiền"
        });
        showTable1();
        //reset1();
        cbMahdnh1.setText(tblPhieunhap.getModel().getValueAt(i, 1).toString());
        //------------------------------------
        listSP = spBLL.getAllSanphamDTO();
        modelsp = (DefaultTableModel) tblSanpham.getModel();
        modelsp.setColumnIdentifiers(new Object[]{
            "STT", "Mã SP", "Tên SP", "Số lượng", "Đơn giá", "Đơn vị tính",
            "Mã loại", "Nhà sản xuất"
        });
        showTableSanpham();
    }//GEN-LAST:event_tblPhieunhapMouseClicked
    public static boolean isNumeric(String str) { //kiểm tra có phải số kiểu INT
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    public static boolean isNumericfloat(String str) { //kiểm tra có phải số kiểu DOUBLE
        try {
            Float.parseFloat(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    private int kt() {
        int fag = 1;
        if (txtMP.getText().length() == 0) {
            fag = 0;
        }
        return fag;
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (kt() == 1) {
            PhieunhapDTO pnDTO = new PhieunhapDTO();
            pnDTO.setMaHDNH(txtMP.getText());
            pnDTO.setMaNV(cbManv.getSelectedItem().toString());
            pnDTO.setMaNCC(cbMancc.getSelectedItem().toString());
            pnDTO.setTongtien(txtTongtien.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(txtNgaylap.getDate());
            pnDTO.setNgaylap(date);
            for (PhieunhapDTO sp : listPN) {
                if (sp.getMaHDNH().equals(txtMP.getText())) {
                    JOptionPane.showMessageDialog(rootPane, "Đã tồn tại mã phiếu");
                    return;
                }
            }
            try {
                if (pnBLL.addPhieunhapDTO(pnDTO)) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                    listPN.add(pnDTO);
                    showResult();
                    reset();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thêm không thành công ");
                }
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(rootPane, "Thêm không thành công ");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thông tin bạn nhập chưa đủ :");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int selectedIndex = tblPhieunhap.getSelectedRow();
        if (listPN.size() == 0) {
            JOptionPane.showMessageDialog(rootPane,
                    "Hãy nhập thêm Phiếu nhập rồi sửa");
        } else if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "Hãy chọn dòng có thông tin  cần sửa rồi ấn sửa");
        } else {
            PhieunhapDTO pnDTO = new PhieunhapDTO();
            pnDTO.setMaHDNH(txtMP.getText());
            pnDTO.setMaNV(cbManv.getSelectedItem().toString());
            pnDTO.setMaNCC(cbMancc.getSelectedItem().toString());
            pnDTO.setTongtien(txtTongtien.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(txtNgaylap.getDate());
            pnDTO.setNgaylap(date);
            try {
                if (pnBLL.suaPhieunhapDTO(pnDTO)) {
                    JOptionPane.showMessageDialog(rootPane, "Sửa thành công !");
                    model.setRowCount(0);
                    listPN = pnBLL.getAllPhieunhapDTO();
                    showTable();
                    reset();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Sửa không thành công 123");
                }
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(rootPane, "Sửa không thành công ");
            }
        }
        btnThem.setEnabled(true);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
        btnThem.setEnabled(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblChitietphieunhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChitietphieunhapMouseClicked
        int i = tblChitietphieunhap.getSelectedRow();
        cbMahdnh1.setText(tblChitietphieunhap.getModel().getValueAt(i, 1).toString());
        cbMasp.setText(tblChitietphieunhap.getModel().getValueAt(i, 2).toString());
        txtSoluong.setText(tblChitietphieunhap.getModel().getValueAt(i, 3).toString());
        txtDongianhap.setText(tblChitietphieunhap.getModel().getValueAt(i, 4).toString());
        txtThanhtien.setText(tblChitietphieunhap.getModel().getValueAt(i, 5).toString());
        //-------------------------------
        btnThem1.setEnabled(false);
        txtThanhtien.setEditable(false);
        cbMasp.setEditable(false);
        cbMahdnh1.setEditable(false);
        txtDongianhap.setEditable(false);

        //--------------------------
    }//GEN-LAST:event_tblChitietphieunhapMouseClicked

    private void txtSoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoluongActionPerformed
        if (isNumericfloat(txtDongianhap.getText())) {
            if (isNumeric(txtSoluong.getText())) {
                int f = Integer.parseInt(txtSoluong.getText());
                float tongtien = (float) (f * Float.parseFloat(txtDongianhap.getText()));
                txtThanhtien.setText(String.valueOf(tongtien));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Số lượng phải là số :");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Chưa nhập đúng đơn giá :");
        }
    }//GEN-LAST:event_txtSoluongActionPerformed

    private void txtThanhtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThanhtienActionPerformed

    }//GEN-LAST:event_txtThanhtienActionPerformed
    public int kt1() {
        int fag = 1;
        if (cbMasp.getText().length() == 0) {
            fag = 0;
        } else if (!isNumericfloat(txtDongianhap.getText())) {
            fag = 0;
        } else if (txtDongianhap.getText().length() == 0) {
            fag = 0;
        } else if (!isNumericfloat(txtDongianhap.getText())) {
            fag = 0;
        } else if (txtSoluong.getText().length() == 0 || !isNumeric(txtSoluong.getText())) {
            fag = 0;
        } else if (txtThanhtien.getText().length() == 0) {
            fag = 0;
        }
        return fag;
    }
    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        int i = tblSanpham.getSelectedRow();
        String temp = tblSanpham.getValueAt(i, 1).toString();
        int temp2 = 0;
        for (int j = 0; j < tblChitietphieunhap.getRowCount(); j++) {
            if (tblChitietphieunhap.getValueAt(j, 2).equals(temp)) {
                temp2 = 1;
                break;
            }
        }
        if (temp2 == 1) {
            JOptionPane.showMessageDialog(rootPane, "Sản phẩm đã tồn tại trong phiếu nhập");
            reset1();
            return;
        }
        if (kt1() == 1) {
            ChitietphieunhapDTO ctpnDTO = new ChitietphieunhapDTO();
            ctpnDTO.setMaHDNH(cbMahdnh1.getText());
            ctpnDTO.setMaSP(cbMasp.getText());
            ctpnDTO.setSoluong(Integer.parseInt(txtSoluong.getText()));
            ctpnDTO.setDongianhap(Float.parseFloat(txtDongianhap.getText()));
            ctpnDTO.setThanhtien(Float.parseFloat(txtThanhtien.getText()));

            try {
                if (ctpnBLL.addChitietphieunhapDTO(ctpnDTO)) {
                    JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
                    listCTPN.add(ctpnDTO);//them vao danh sach
                    showResult1();
                    // reset1();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Thêm không thành công ");
                }
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(rootPane, "Thêm không thành công ");
            }
        }
        reset();
        tongtienupdate(cbMahdnh1.getText());
        //--------UPDATE SO LUONG
        int t = ctpnBLL.getSoluong(cbMasp.getText());
        int k1 = Integer.parseInt(txtSoluong.getText());
        int slcl = t + k1;
        soluongupdate(slcl, cbMasp.getText());
        reset1();
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        if (kt1() == 1) {
            int slbd = ctpnBLL.laysoluongsp(cbMasp.getText(), cbMahdnh1.getText());
            ChitietphieunhapDTO ctpnDTO = new ChitietphieunhapDTO();
            ctpnDTO.setMaHDNH(cbMahdnh1.getText());
            ctpnDTO.setMaSP(cbMasp.getText());
            ctpnDTO.setSoluong(Integer.parseInt(txtSoluong.getText()));
            ctpnDTO.setDongianhap(Float.parseFloat(txtDongianhap.getText()));
            ctpnDTO.setThanhtien(Float.parseFloat(txtThanhtien.getText()));

            try {
                if (ctpnBLL.suaChitietphieunhapDTO(ctpnDTO)) {
                    JOptionPane.showMessageDialog(rootPane, "Sửa thành công !");
                    model1.setRowCount(0);
                    listCTPN = ctpnBLL.getChitietphieunhapDTO(cbMahdnh1.getText());
                    showTable1();
                    // reset1();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Sửa không thành công 123 ");
                }
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(rootPane, "Sửa không thành công ");
            }
            reset();
            tongtienupdate(cbMahdnh1.getText());
            btnThem1.setEnabled(true);

            //--------UPDATE SO LUONG
            //      Số lượng sản phẩm ban đầu
            //      int slbd =cthdBLL.laysoluongsp(cbMasp.getText(),cbMahd.getText());
            //      Số lượng sản phẩm có trong kho
            int t = ctpnBLL.getSoluong(cbMasp.getText());
            //      So lượng sản phẩm đã sửa thành
            int k = Integer.parseInt(txtSoluong.getText());
            int slcl = 0;
            if (k > slbd) {
                int f = k - slbd;
                slcl = t + f;
            } else {
                int f = slbd - k;
                slcl = t - f;
            }
            soluongupdate(slcl, cbMasp.getText());
            reset1();
            //-------
        } else {
            JOptionPane.showMessageDialog(rootPane, "Thông tin chưa đủ");
        }

    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        //int i = tblPhieunhap.getSelectedRow();
        int slbd = ctpnBLL.laysoluongsp(cbMasp.getText(), cbMahdnh1.getText());
        int removeIndex = tblChitietphieunhap.getSelectedRow();
        if (removeIndex == -1) {
            JOptionPane.showMessageDialog(rootPane,
                    "Hãy chọn một dòng rồi ấn nút xóa");
        } else if (listCTPN.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane,
                    "Không có thông tin  nào để xóa");
        } else {
            ChitietphieunhapDTO ctpnDTO = new ChitietphieunhapDTO();
            ctpnDTO.setMaHDNH(cbMahdnh1.getText());
            ctpnDTO.setMaSP(cbMasp.getText());
            if (JOptionPane.showConfirmDialog(this, "Delete chi tiết hóa đơn ?", "Confirm",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (ctpnBLL.xoaChitietphieunhapDTO(ctpnDTO)) {
                    model1.setRowCount(0);
                    listCTPN = ctpnBLL.getChitietphieunhapDTO(cbMahdnh1.getText());
                    //reset1();
                    //cbMahdnh1.setText("");
                    showTable1();
                } else {
                    JOptionPane.showMessageDialog(rootPane, " Xóa không thành công DAL");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Bạn đã không đồng ý xóa ");
            }
        }
        reset();
        tongtienupdate(cbMahdnh1.getText());
        btnThem1.setEnabled(true);
        //--------UPDATE SO LUONG
        int t = ctpnBLL.getSoluong(cbMasp.getText());
        int slcl = t - slbd;
        soluongupdate(slcl, cbMasp.getText());
        reset1();
        //-------
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        reset1();
        btnThem1.setEnabled(true);
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void tblSanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanphamMouseClicked
        int i = tblSanpham.getSelectedRow();
        cbMasp.setText(tblSanpham.getModel().getValueAt(i, 1).toString());
        cbMasp.setEnabled(false);
    }//GEN-LAST:event_tblSanphamMouseClicked

    private void jScrollPane6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane6MouseClicked

    }//GEN-LAST:event_jScrollPane6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JTextField cbMahdnh1;
    private javax.swing.JComboBox<String> cbMancc;
    private javax.swing.JComboBox<String> cbManv;
    private javax.swing.JTextField cbMasp;
    private javax.swing.JComboBox<String> cbTimkimhoadonnhaphang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tblChitietphieunhap;
    private javax.swing.JTable tblPhieunhap;
    private javax.swing.JTable tblSanpham;
    private javax.swing.JTextField txtDongianhap;
    private javax.swing.JTextField txtMP;
    private com.toedter.calendar.JDateChooser txtNgaylap;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtThanhtien;
    private javax.swing.JTextField txtTimkiemhoadonnhaphang;
    private javax.swing.JTextField txtTongtien;
    private javax.swing.JTextField txtTongtienphieunhap;
    // End of variables declaration//GEN-END:variables
public void showTable() {
        model.setRowCount(0);
        int i = 1;
        for (PhieunhapDTO pnDTO : listPN) {
            model.addRow(new Object[]{
                i++, pnDTO.getMaHDNH(), pnDTO.getMaNV(), pnDTO.getMaNCC(), pnDTO.getTongtien(), pnDTO.getNgaylap()
            });
        }
    }

    public void showTable1() {
        int i = 1;
        model1.setRowCount(0);
        for (ChitietphieunhapDTO ctpnDTO : listCTPN) {
            model1.addRow(new Object[]{
                i++, ctpnDTO.getMaHDNH(), ctpnDTO.getMaSP(), ctpnDTO.getSoluong(), ctpnDTO.getDongianhap(), ctpnDTO.getThanhtien()
            });
        }
    }

    public void showResult() {
        int i = listPN.size();
        PhieunhapDTO pnDTO = listPN.get(listPN.size() - 1);
        model.addRow(new Object[]{
            i++, pnDTO.getMaHDNH(), pnDTO.getMaNV(), pnDTO.getMaNCC(), pnDTO.getTongtien(), pnDTO.getNgaylap()
        });
    }

    public void showResult1() {
        int i = listCTPN.size();
        ChitietphieunhapDTO ctpnDTO = listCTPN.get(listCTPN.size() - 1);
        model1.addRow(new Object[]{
            i++, ctpnDTO.getMaHDNH(), ctpnDTO.getMaSP(), ctpnDTO.getSoluong(), ctpnDTO.getDongianhap(), ctpnDTO.getThanhtien()
        });
    }

    public void reset() {
        txtMP.setText("");
        txtMP.setEditable(true);
        cbManv.setSelectedIndex(0);
        cbMancc.setSelectedIndex(0);
        txtDongianhap.setText("");
        txtTongtien.setText("0");
        txtNgaylap.setDate(new Date());
        txtNgaylap.setEnabled(true);
    }

    public void reset1() {
        cbMasp.setEnabled(true);
        cbMasp.setText("");
        txtSoluong.setText("");
        txtDongianhap.setEditable(true);
        txtDongianhap.setText("");
        txtThanhtien.setText("");
    }

    public void showTableSanpham() {
        int i = 1;
        modelsp.setRowCount(0);
        for (SanphamDTO spDTO : listSP) {
            modelsp.addRow(new Object[]{
                i++, spDTO.getMasp(), spDTO.getTensp(), spDTO.getSoluong(),
                spDTO.getDongia(), spDTO.getDonvitinh(),
                spDTO.getMaloai(), spDTO.getMaNSX()
            });
        }
    }

    public void tongtienupdate(String mapn) {
        float t = ctpnBLL.Tongtien(mapn);
        String s = String.valueOf(t);
        txtTongtienphieunhap.setText(s);
        ctpnBLL.suaTongtien(t, mapn);
//        listPN = new PhieunhapBLL().getAllPhieunhapDTO();
//        showTable();

    }

    public void soluongupdate(int soluong, String masp) {
        ctpnBLL.suasoluong(soluong, masp);
        listSP = new SanphamBLL().getAllSanphamDTO();
        showTableSanpham();
        listPN = new PhieunhapBLL().getAllPhieunhapDTO();
        showTable();
        listCTPN = new ChitietphieunhapBLL().getChitietphieunhapDTO(cbMahdnh1.getText());
        showTable1();
    }

    protected void updateFilter() {
        Object selected = cbTimkimhoadonnhaphang.getSelectedItem();
        TableRowSorter<TableModel> sorter = (TableRowSorter<TableModel>) tblPhieunhap.getRowSorter();
        String text = "(?i)" + txtTimkiemhoadonnhaphang.getText();
        int col = -1;
        if ("Mã HDNH".equals(selected)) {
            col = 1;
        } else if ("Mã NCC".equals(selected)) {
            col = 3;
        } else if ("Mã NV".equals(selected)) {
            col = 2;
        } else if ("Ngày lập".equals(selected)) {
            col = 5;
        }
        sorter.setRowFilter(RowFilter.regexFilter(text, col));
    }
}
