/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.TaikhoanBLL;
import java.awt.Color;
import java.awt.Event;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author MYPC
 */
public class Trangchu extends javax.swing.JFrame {

    /**
     * Creates new form Trangchu
     */
    public Trangchu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public Trangchu(String a) {
        initComponents();
         try {
            UIManager.setLookAndFeel(new com.jtattoo.plaf.graphite.GraphiteLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(Trangchu.class.getName()).log(Level.SEVERE, null, ex);
        } 
        setLocationRelativeTo(null);
        TaikhoanBLL tkBLL = new TaikhoanBLL();
        if(tkBLL.getRole(a).equals("user"))
            btnTaikhoan.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSanpham = new javax.swing.JButton();
        btnHoadon = new javax.swing.JButton();
        btnNhacc = new javax.swing.JButton();
        btnKhachhang = new javax.swing.JButton();
        btnNhanvien = new javax.swing.JButton();
        btnThongke = new javax.swing.JButton();
        btnDangxuat = new javax.swing.JButton();
        homedesktop = new javax.swing.JDesktopPane();
        btnLoaisp = new javax.swing.JButton();
        btnPhieunhap = new javax.swing.JButton();
        btnNhasx = new javax.swing.JButton();
        btnKhuyenmai = new javax.swing.JButton();
        btnSpkm = new javax.swing.JButton();
        btnTaikhoan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trang chủ");
        setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cogai.png"))); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/comvecteezy450003.jpg"))); // NOI18N
        jButton1.setText("Trang chủ");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        jButton1.setPreferredSize(new java.awt.Dimension(155, 69));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSanpham.setBackground(new java.awt.Color(255, 255, 255));
        btnSanpham.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSanpham.setForeground(new java.awt.Color(0, 0, 51));
        btnSanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sanpham.png"))); // NOI18N
        btnSanpham.setText("Sản phẩm");
        btnSanpham.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        btnSanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanphamActionPerformed(evt);
            }
        });

        btnHoadon.setBackground(new java.awt.Color(255, 255, 255));
        btnHoadon.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnHoadon.setForeground(new java.awt.Color(0, 0, 51));
        btnHoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hoadon.png"))); // NOI18N
        btnHoadon.setText("  Hóa đơn");
        btnHoadon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        btnHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoadonActionPerformed(evt);
            }
        });

        btnNhacc.setBackground(new java.awt.Color(255, 255, 255));
        btnNhacc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNhacc.setForeground(new java.awt.Color(0, 0, 51));
        btnNhacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doitac.png"))); // NOI18N
        btnNhacc.setText("Nhà cung cấp");
        btnNhacc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        btnNhacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhaccActionPerformed(evt);
            }
        });

        btnKhachhang.setBackground(new java.awt.Color(255, 255, 255));
        btnKhachhang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnKhachhang.setForeground(new java.awt.Color(0, 0, 51));
        btnKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/khachHang.png"))); // NOI18N
        btnKhachhang.setText("Khách hàng");
        btnKhachhang.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        btnKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachhangActionPerformed(evt);
            }
        });

        btnNhanvien.setBackground(new java.awt.Color(255, 255, 255));
        btnNhanvien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNhanvien.setForeground(new java.awt.Color(0, 0, 51));
        btnNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nhanvien.png"))); // NOI18N
        btnNhanvien.setText("Nhân viên");
        btnNhanvien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        btnNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanvienActionPerformed(evt);
            }
        });

        btnThongke.setBackground(new java.awt.Color(255, 255, 255));
        btnThongke.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnThongke.setForeground(new java.awt.Color(0, 0, 51));
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doanhthu.png"))); // NOI18N
        btnThongke.setText("Thống kê");
        btnThongke.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });

        btnDangxuat.setBackground(new java.awt.Color(255, 255, 255));
        btnDangxuat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDangxuat.setForeground(new java.awt.Color(204, 0, 0));
        btnDangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thoat.png"))); // NOI18N
        btnDangxuat.setText("Đăng xuât");
        btnDangxuat.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        btnDangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangxuatActionPerformed(evt);
            }
        });

        homedesktop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout homedesktopLayout = new javax.swing.GroupLayout(homedesktop);
        homedesktop.setLayout(homedesktopLayout);
        homedesktopLayout.setHorizontalGroup(
            homedesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1461, Short.MAX_VALUE)
        );
        homedesktopLayout.setVerticalGroup(
            homedesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btnLoaisp.setBackground(new java.awt.Color(255, 255, 255));
        btnLoaisp.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnLoaisp.setForeground(new java.awt.Color(0, 0, 51));
        btnLoaisp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/All-512.png"))); // NOI18N
        btnLoaisp.setText("Loại SP   ");
        btnLoaisp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));
        btnLoaisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaispActionPerformed(evt);
            }
        });

        btnPhieunhap.setBackground(new java.awt.Color(255, 255, 255));
        btnPhieunhap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPhieunhap.setForeground(new java.awt.Color(0, 0, 51));
        btnPhieunhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/import.png"))); // NOI18N
        btnPhieunhap.setText("Phiếu nhập");
        btnPhieunhap.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));
        btnPhieunhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhieunhapActionPerformed(evt);
            }
        });

        btnNhasx.setBackground(new java.awt.Color(255, 255, 255));
        btnNhasx.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnNhasx.setForeground(new java.awt.Color(0, 0, 51));
        btnNhasx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconnhamay.png"))); // NOI18N
        btnNhasx.setText("Nhà SX   ");
        btnNhasx.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));
        btnNhasx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhasxActionPerformed(evt);
            }
        });

        btnKhuyenmai.setBackground(new java.awt.Color(255, 255, 255));
        btnKhuyenmai.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnKhuyenmai.setForeground(new java.awt.Color(0, 0, 51));
        btnKhuyenmai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/discount.png"))); // NOI18N
        btnKhuyenmai.setText("KM        ");
        btnKhuyenmai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));
        btnKhuyenmai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuyenmaiActionPerformed(evt);
            }
        });

        btnSpkm.setBackground(new java.awt.Color(255, 255, 255));
        btnSpkm.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSpkm.setForeground(new java.awt.Color(0, 0, 51));
        btnSpkm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/discountitem.png"))); // NOI18N
        btnSpkm.setText("SP_KM");
        btnSpkm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));
        btnSpkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpkmActionPerformed(evt);
            }
        });

        btnTaikhoan.setBackground(new java.awt.Color(255, 255, 255));
        btnTaikhoan.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnTaikhoan.setForeground(new java.awt.Color(0, 0, 51));
        btnTaikhoan.setText("Tài khoản");
        btnTaikhoan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102), new java.awt.Color(102, 0, 102)));
        btnTaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaikhoanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PHẦN MỀM QUẢN LÍ CỬA HÀNG MỸ PHẨM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDangxuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(homedesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnNhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNhacc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(btnThongke, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSanpham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHoadon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnKhachhang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPhieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNhasx, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSpkm, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homedesktop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLoaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNhasx, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPhieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSpkm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed
    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        ThongkeGUI tk = new ThongkeGUI();
        tk.setClosable(true); 
        int x = (homedesktop.getWidth() - tk.getWidth())/2;
        int y = (homedesktop.getHeight()- tk.getHeight())/2;
        tk.setLocation(x, y);
        homedesktop.add(tk);
        tk.setVisible(true);
    }//GEN-LAST:event_btnThongkeActionPerformed

    private void btnSanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanphamActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        SanphamGUI tk = new SanphamGUI();
        tk.setClosable(true); 
        int x = (homedesktop.getWidth() - tk.getWidth())/2;
        int y = (homedesktop.getHeight()- tk.getHeight())/2;
        tk.setLocation(x, y);
        homedesktop.add(tk);
        tk.setVisible(true);
    }//GEN-LAST:event_btnSanphamActionPerformed

    private void btnHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoadonActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        HoadonGUI tk = new HoadonGUI();
        tk.setClosable(true); 
        int x = (homedesktop.getWidth() - tk.getWidth())/2;
        int y = (homedesktop.getHeight()- tk.getHeight())/2;
        tk.setLocation(x, y);
        homedesktop.add(tk);
        tk.setVisible(true);

    }//GEN-LAST:event_btnHoadonActionPerformed

    private void btnKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachhangActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        KhachhangGUI kh = new KhachhangGUI();
        kh.setClosable(true); 
        int x = (homedesktop.getWidth() - kh.getWidth())/2;
        int y = (homedesktop.getHeight()- kh.getHeight())/2;
        kh.setLocation(x, y);
        homedesktop.add(kh);
        kh.setVisible(true);

    }//GEN-LAST:event_btnKhachhangActionPerformed

    private void btnNhaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhaccActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        NhacungcapGUI kh = new NhacungcapGUI();
        kh.setClosable(true); 
        int x = (homedesktop.getWidth() - kh.getWidth())/2;
        int y = (homedesktop.getHeight()- kh.getHeight())/2;
        kh.setLocation(x, y);
        homedesktop.add(kh);
        kh.setVisible(true);
    }//GEN-LAST:event_btnNhaccActionPerformed

    private void btnNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanvienActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        NhanvienGUI kh = new NhanvienGUI();
        kh.setClosable(true); 
        int x = (homedesktop.getWidth() - kh.getWidth())/2;
        int y = (homedesktop.getHeight()- kh.getHeight())/2;
        kh.setLocation(x, y);
        homedesktop.add(kh);
        kh.setVisible(true);
    }//GEN-LAST:event_btnNhanvienActionPerformed

    private void btnDangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangxuatActionPerformed

        if (JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thoát khỏi hệ thống ?", "Confirm",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
            TaikhoandangnhapGUI tk = new TaikhoandangnhapGUI(this, rootPaneCheckingEnabled);
            tk.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nhiều chuyện !");
        }
    }//GEN-LAST:event_btnDangxuatActionPerformed

    private void btnLoaispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaispActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        LoaisanphamGUI kh = new LoaisanphamGUI();
        kh.setClosable(true); 
        int x = (homedesktop.getWidth() - kh.getWidth())/2;
        int y = (homedesktop.getHeight()- kh.getHeight())/2;
        kh.setLocation(x, y);
        homedesktop.add(kh);
        kh.setVisible(true);
    }//GEN-LAST:event_btnLoaispActionPerformed

    private void btnNhasxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhasxActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        NhasanxuatGUI kh = new NhasanxuatGUI();
        kh.setClosable(true); 
        int x = (homedesktop.getWidth() - kh.getWidth())/2;
        int y = (homedesktop.getHeight()- kh.getHeight())/2;
        kh.setLocation(x, y);
        homedesktop.add(kh);
        kh.setVisible(true);
    }//GEN-LAST:event_btnNhasxActionPerformed

    private void btnPhieunhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhieunhapActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        PhieunhapGUI kh = new PhieunhapGUI();
        kh.setClosable(true); 
        int x = (homedesktop.getWidth() - kh.getWidth())/2;
        int y = (homedesktop.getHeight()- kh.getHeight())/2;
        kh.setLocation(x, y);
        homedesktop.add(kh);
        kh.setVisible(true);
    }//GEN-LAST:event_btnPhieunhapActionPerformed

    private void btnKhuyenmaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuyenmaiActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        ChuongtrinhkhuyenmaiGUI kh = new ChuongtrinhkhuyenmaiGUI();
        kh.setClosable(true); 
        int x = (homedesktop.getWidth() - kh.getWidth())/2;
        int y = (homedesktop.getHeight()- kh.getHeight())/2;
        kh.setLocation(x, y);
        homedesktop.add(kh);
        kh.setVisible(true);
    }//GEN-LAST:event_btnKhuyenmaiActionPerformed

    private void btnSpkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpkmActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        Sanpham_KhuyenmaiGUI kh = new Sanpham_KhuyenmaiGUI();
        kh.setClosable(true); 
        int x = (homedesktop.getWidth() - kh.getWidth())/2;
        int y = (homedesktop.getHeight()- kh.getHeight())/2;
        kh.setLocation(x, y);
        homedesktop.add(kh);
        kh.setVisible(true);
    }//GEN-LAST:event_btnSpkmActionPerformed

    private void btnTaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaikhoanActionPerformed
        homedesktop.removeAll();
        homedesktop.updateUI();
        TaikhoanGUI kh = new TaikhoanGUI();
        kh.setClosable(true); 
        int x = (homedesktop.getWidth() - kh.getWidth())/2;
        int y = (homedesktop.getHeight()- kh.getHeight())/2;
        kh.setLocation(x, y);
        homedesktop.add(kh);
        kh.setVisible(true);
    }//GEN-LAST:event_btnTaikhoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trangchu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trangchu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangxuat;
    private javax.swing.JButton btnHoadon;
    private javax.swing.JButton btnKhachhang;
    private javax.swing.JButton btnKhuyenmai;
    private javax.swing.JButton btnLoaisp;
    private javax.swing.JButton btnNhacc;
    private javax.swing.JButton btnNhanvien;
    private javax.swing.JButton btnNhasx;
    private javax.swing.JButton btnPhieunhap;
    private javax.swing.JButton btnSanpham;
    private javax.swing.JButton btnSpkm;
    private javax.swing.JButton btnTaikhoan;
    private javax.swing.JButton btnThongke;
    private javax.swing.JDesktopPane homedesktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
